spring.application.name=nts_prj
spring.docker.compose.file=./resource/docker-compose.yaml
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3305/mydb
spring.datasource.username=son.nguyen12
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.order_updates=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
