services:
  mysql:
    container_name: my-db-mysql
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mydb
      MYSQL_USER: son.nguyen12
      MYSQL_PASSWORD: 123456
    ports:
      - 3305:3306
    volumes:
      - ./mysql-init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5